version: 0.0
os: windows

files:
  - source: /
    destination: C:\inetpub\wwwroot\myapp

hooks:
  BeforeInstall:
    - location: scripts\stop_server.ps1
      timeout: 300
  AfterInstall:
    - location: scripts\start_server.ps1
      timeout: 300
