version: 0.0
os: windows
files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.bat
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts/start_server.bat
      timeout: 300
      runas: Administrator
  ApplicationStop:
    - location: scripts/stop_server.bat
      timeout: 300
      runas: Administrator
