version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing .NET 6 SDK
      - choco install dotnet-sdk --version 6.0.100 -y

  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore

  build:
    commands:
      - echo Building the API project
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Running unit tests
      - dotnet test --no-restore --verbosity normal
