version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_windows_amd64.zip
      - Expand-Archive -Path terraform_1.4.6_windows_amd64.zip -DestinationPath 'C:\terraform'
      - setx /M PATH "$env:PATH;C:\terraform"

build:
  commands:
    - echo "Expanding archive..."
    - curl -LO https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_windows_amd64.zip
      - Expand-Archive -Path terraform_1.4.6_windows_amd64.zip -DestinationPath 'C:\terraform'
      - setx /M PATH "$env:PATH;C:\terraform"
      - terraform plan
